### ISSUE TITLE
Repository Structure

### ISSUE THREAD

**Issue by Anthony-Jhoiro** [selflow/selflow#56]
The current repository structure can be improved. The main issue is that Selflow should support plugins in any language. 

The current structure is a mix of the standard go structure and the nx structure. Maybe refactoring the code only to use the nx structure is a better idea.

This can looks like something like this:

```
.
├── apps              # Applications and e2e tests for those applications
├── libs
│   ├── core          # Selflow core-libraries
│   ├── [app-name]    # Libraries specifics to [app-name]
│   ├── protos        # Protobufs
│   └── ui            # Libraries shared by all UI projects
├── docs              # Markdown documentation
└── assets            # Assets for the main README
```

*I'm open to suggestions*

**Comment by beaussan** [comment]
I think it's sane, and it looks pretty good !

One note, since nx 17, you don't _have to_ stick with `apps` and `libs` (see [as provided vs. derived](https://nx.dev/deprecated/as-provided-vs-derived#as-provided-vs-derived-generator-path-options)), but I think the separation is a good thing. This will allow for expansion with a bit of isolations needed :)

**Comment by Anthony-Jhoiro** [comment]
Thank's @beaussan! 
I missed this new feature! That's very interesting! Currently, the repository is still using version 15 of NX. But I plan to migrate it to NX 17 in the next few weeks, mainly for dynamic targets (for all the Go projects) and the possibilities offered by the evolution of the `nx show` command. 
If you have any recommendations, I would be happy to hear them!

**Comment by beaussan** [comment]
The dinamic target is definitely interesting, I've fiddled a bit with them last month and I love what they enable. I could be useful for a polyglot repo, that's for sure!
